### ISSUE TITLE
Production Checklist

### ISSUE THREAD

**Issue by ozerugae** [shan916/safe-rides#166]
The following final steps should be performed. Preferably in order.
_Things in italics are optional_
- [x] Update Spring Boot to 1.5.8 (see comments below)
- [x] Dependency injection via constructor as opposed to member
- [ ] Caching
  - [ ] Driver
  - [ ] User
  - [ ] Roles
- [ ] _Trim unused CSS/JS_
- [x] Update Javadocs comments
- [x] Update Swagger documentation annotations
- [x] Remove start-up code in the command line runner bean thingy
- [ ] _Move logic to service layer_
- [x] _Encrypt database at rest_
- [ ] Create test script
  - [x] List of all features and the api actions necessary
  - [x] Test via each role
  - [ ] Check for information leaks
  - [ ] _Possibly automate testing (system/integration)_
  - [ ] Record results
- [ ] Maintenance documentation
  - [ ] API
    - [ ] Compiling from source
    - [ ] Application settings
      - [ ] Geocoding API key
    - [ ] Setting up the database 
      - [ ] Structure
      - [ ] Seeding database
        - [ ] Admin user
        - [ ] Initial configuration (key = 1)
    - [ ] Log output to file
    - [ ] Starting the API
    - [ ] _Set up as service_
    - [ ] _Backup instructions (mysqldump during off-hours?)_
  - [ ] Client (AngularJS)
    - [ ] Application settings
      - [ ] Map API key
      - [ ] Disable debug logging
    - [ ] Packaging for release
      - [ ] Possibly separate "builds" for riders, drivers, coordinators/admins
- [ ] User documentation - let Reuben know that they can create or update the docs themselves :)
